movieapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('movies.urls')),
    path('admin/', admin.site.urls),
]

movies/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views
app_name='movies'
urlpatterns = [
    path('',views.HomeView.as_view(),name='Home'),
    path('login',views.loginview,name='Login'),
    path('logout',views.logoutview,name='lgout'),
    path('register',views.registerview,name='Register'),
    path('add',views.addmovieview,name='Add'),
    path('addmovie',views.addmovieview,name='AddMovie'),
    path('view',views.MoviesView.as_view(),name='View'),
    path('edit',login_required(views.EditView.as_view()),name='Edit'),
    path('edit/<int:pk>',views.updatemovieview,name='EditMovie'),
    path('update/<int:pk>',views.updatemovieview,name='UpdateMovie')
]

movies/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class Movie(models.Model):
    movie_name=models.CharField(max_length=300)
    movie_release_date=models.DateField()
    movie_summary=models.CharField(max_length=10000)
    def __str__(self):
        return self.movie_name+', released on '+str(self.movie_release_date)

class User(AbstractUser,models.Model):
    username=models.CharField(max_length=100,unique=True)
    password=models.CharField(max_length=400)
    name=models.CharField(max_length=100)
    class Meta(AbstractUser.Meta):
        swappable='AUTH_USER_MODEL'
    def __str__(self):
        return self.name+' has username '+self.username

movies/forms.py
from django import forms
from .models import Movie,User
from django.shortcuts import get_object_or_404

#Constants
FORM_FIELD_CLASS='form-control mb-1'

class DateInput(forms.DateInput):
    input_type='date'

class AddMovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['movie_name','movie_release_date','movie_summary']
        widgets={
            'movie_name':forms.TextInput(attrs={'class':FORM_FIELD_CLASS}),
            'movie_release_date':DateInput(attrs={'class':FORM_FIELD_CLASS}),
            'movie_summary':forms.Textarea(attrs={'cols':80,'rows':8,'class':FORM_FIELD_CLASS})
        }

class LoginForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={'class':FORM_FIELD_CLASS}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={'class':FORM_FIELD_CLASS}))
    fields=['username','password']
    def valid_login(self):
        data=self.cleaned_data
        user=data['username']
        pwd=data['password']
        try:
            u=User.objects.get(username=user,password=pwd)
            self.user=u
        except User.DoesNotExist:
            return False
        return True
    def get_user(self):
        return self.user

class RegisterForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','name','password']
        widgets={
            'username':forms.TextInput(attrs={'class':FORM_FIELD_CLASS}),
            'password':forms.PasswordInput(attrs={'class':FORM_FIELD_CLASS})
        }

movies/views.py
from django.shortcuts import render,reverse,get_object_or_404
from django.views import generic
from django.http import HttpResponseRedirect
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required
from .models import Movie
from .forms import AddMovieForm,LoginForm,RegisterForm

#Constants
HOME_PAGE='movies:Home'


# Create your views here.

class HomeView(generic.ListView):
    template_name='movies/Home.html'
    def get_queryset(self):
        return 

class MoviesView(generic.ListView):
    template_name='movies/View.html'
    context_object_name='movies_list'
    def get_queryset(self):
        return Movie.objects.all()

class EditView(generic.ListView):
    template_name='movies/Edit.html'
    context_object_name='movies_list'
    def get_queryset(self):
        return Movie.objects.all()

class EditMovieView(generic.DetailView):
    model=Movie
    template_name='movies/EditMovie.html'

@login_required(login_url='/login')
def addmovieview(request):
    print(request.user)
    if request.method=='POST':
        form=AddMovieForm(request.POST)
        if form.is_valid():
            post=form.save()
            return HttpResponseRedirect(reverse(HOME_PAGE))
    else:
        form=AddMovieForm()
    return render(request,'movies/Add.html',{'form':form})

def updatemovieview(request,pk):
    movie=get_object_or_404(Movie,pk=pk)
    if request.method=='POST':
        form=AddMovieForm(request.POST,instance=movie)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse(HOME_PAGE))
    else:
        form=AddMovieForm(instance=movie)
    return render(request,'movies/EditMovie.html',{'form':form,'id':pk,'movie':movie.movie_name})

def loginview(request):
    if request.method=='POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            if form.valid_login():
                user=form.get_user()
                login(request,user)
                return HttpResponseRedirect(reverse(HOME_PAGE))
    else:
        form=LoginForm()
    return render(request,'movies/Login.html',{'form':form})

def registerview(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            user=form.save()
            print(user)
            print(type(user))
            login(request,user)
            return HttpResponseRedirect(reverse(HOME_PAGE))
    else:
        form=RegisterForm()
    return render(request,'movies/Register.html',{'form':form})

def logoutview(request):
    logout(request)
    return HttpResponseRedirect(reverse('movies:Login'))

movies/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'movies/css/Home.css' %}">
</head>

<body>
    <div class="body">
        {% block content %}{% endblock %}
    </div>
</body>

</html>

movies/templates/movies/Add.html
{% extends "base.html" %} {% block title %}Add Movie{% endblock %} {% block content %}
<div class="head">
    <h1>Add Movie</h1>
</div>
<div class="body">
    <form action="{% url 'movies:AddMovie' %}" method="POST">
        <table>
            {% csrf_token %} {{ form.as_table }}
        </table>
        <input type="submit" class="btn btn-primary" value="ADD MOVIE" />

    </form>
</div>
{% endblock %}

movies/templates/movies/Edit.html
{% extends "base.html" %} {% block title %}Edit Movies{% endblock %} {% block content %}
<div class="movies">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">
                    S. No
                </th>
                <th scope="col">
                    Movie Name
                </th>
                <th scope="col">
                    Release Date
                </th>
                <th scope="col">
                    Summary
                </th>
            </tr>
        </thead>
        <tbody>
            {% for movie in movies_list %}
            <tr>
                <td scope="row">
                    {{forloop.counter}}
                </td>
                <td>
                    <a href="{% url 'movies:EditMovie' movie.id%}">{{movie.movie_name}}</a>
                </td>
                <td>
                    {{movie.movie_release_date}}
                </td>
                <td>
                    {{movie.movie_summary}}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

movies/templates/movies/EditMovie.html
{% extends "base.html" %} {% block title %}Edit Movie: {{movie}}{% endblock %} {% block content %}
<div class="head">
    <h1>Edit Movie</h1>
</div>
<div class="body">
    <form action="{% url 'movies:UpdateMovie' id %}" method="POST">
        <table>
            {% csrf_token %}{{form.as_table}}
        </table>
        <input type="submit" value="UPDATE MOVIE DETAILS" />
    </form>
</div>
{% endblock %}

movies/templates/movies/Home.html
{% extends "base.html" %} {% block title %}Movies App{% endblock %} {% block content %}
<div class="head">
    <h1>Movies App</h1>
</div>
<div class="body">
    <h3>Click on Links To Navigate:</h3>
    <ul>
        <li>
            <a href="{% url 'movies:Home' %}">Home</a>
        </li>
        <li>
            <a href="{% url 'movies:View' %}">View Movies</a>
        </li>
        <li>
            <a href="{% url 'movies:Add' %}">Add Movie</a>
        </li>
        <li>
            <a href="{% url 'movies:Edit' %}">Edit Movie</a>
        </li>
    </ul>
</div>
{% endblock %}

movies/templates/movies/Login.html
{% extends 'base.html' %} {% block title %}Login to Movies Portal{% endblock %} {% block content %}
<form action="/login" method='POST'>
    {% csrf_token %}
    <table>
        {{form.as_table}}
        <tr>
            <td colspan="2">
                <input type="submit" value="LOGIN" class="btn btn-primary">
            </td>
        </tr>
    </table>
</form>

{% endblock %}

movies/templates/movies/Register.html
{% extends 'base.html' %} {% block title %}Register to Movies Portal{% endblock %} {% block content %}
<form action="/register" method='POST'>
    {% csrf_token %}
    <table>
        {{form.as_table}}
        <tr>
            <td colspan="2">
                <input type="submit" value="REGISTER" class="btn btn-primary">
            </td>
        </tr>
    </table>
</form>

{% endblock %}

movies/templates/movies/View.html
{% extends "base.html" %} {% block title %}View Movies{% endblock %} {% block content %}
<div class="movies row">
    {% for movie in movies_list %}
    <div class="col-sm-3">
        <div class="movie card h-100" style="width: 18rem">
            <div class="card-body text-center">
                <h1 class="movie-name card-title">{{movie.movie_name}}</h1>
                <h2 class="movie-release-date card-subtitle mb-2 text-muted">{{movie.movie_release_date}}</h2>
                <p class="movie-summary card-text">{{movie.movie_summary}}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}